name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - name: Lint with Ruff and Black
      run: |
        . venv/bin/activate
        ruff .
        black --check .
    - name: Test with pytest
      run: |
        . venv/bin/activate
        pytest
    - name: Build docs
      run: |
        . venv/bin/activate
        sphinx-build -b html docs/ docs/_build/html

