name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # oder die Python-Version, die dein Projekt verwendet

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff to check code
      run: ruff check .
